# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5683686c5c6af3df304ee6517d9837875529b1c87021f922835ebf4cbbb5761bc2f027c989a1e5f3668d481ddfb576a97795d2e49383895722b49fba31fbf0c

test:
  secret_key_base: 2d37deac014b19fc1c180516087e8a108292a1387307c96733c846d709eea16dadae085659606778ae3f972b12b0ae2350de6ef168b9dc4dc43cd1ea60dd4cfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
